server:
  port: 8080 #端口号
  servlet:
    context-path: /library #项目名,main启动有效
    session:
      timeout: 30m #session超时时间（秒）,main启动有效
  max-http-header-size: 102400

spring:
  datasource: #数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: 123456
    testOnBorrow: true #解决mysql8小时问题
    validation-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 2048MB # 最大支持文件大小
      max-request-size: 2048MB # 最大支持请求大小
      location: ${my.property.root-path}/tmp
  jmx:
    enabled: false
    default-domain: springboot-mybatisplus
  main:
    allow-circular-references: true #允许循环依赖（两个bean相互注入）
  freemarker:
    suffix: .ftl
    cache: false
    charset: utf-8
    check-template-location: true
    expose-request-attributes: true
    request-context-attribute: request
    content-type: text/html
    template-loader-path: classpath:/templates

mybatis-plus:
  mapper-locations: classpath:com/mind/demo/springboot/mybatisplus/mapper/xml/*Mapper.xml
  block-attack: true #防止全表更新、删除，默认true
  pagination:
    overflow: false #溢出总页数，设置第一页，默认true
    max-limit: 20000 #单页分页条数限制，默认10000行
  global-config:
    db-config:
      select-strategy: not_empty #查询条件判空

logback:
  app-name: library #日志项目名称
  pattern: colorful #日志输出样式：default-默认；colorful-彩色（用于开发阶段）
  max-file-size: 3GB #最大文件大小
  max-history: 14 #最大日志保存天数（超过日期的会自动删除掉）